const { Schema, model } = require('mongoose')

// ── Brand knowledge chunk ────────────────────────────────────────────────────
const brandSourceSchema = new Schema(
  {
    type: {
      type: String,
      enum: ['text', 'pdf', 'url'],
      required: true,
    },
    // Human-readable label (filename, URL, or "Manual text")
    label: { type: String, default: '' },
    // Extracted/raw text content (stored after parsing)
    content: { type: String, default: '' },
    // GCS path if the original file was uploaded (PDFs)
    gcsPath: { type: String, default: null },
  },
  { _id: true, timestamps: true }
)

// ── Main Influencer schema ───────────────────────────────────────────────────
const influencerSchema = new Schema(
  {
    // Owner
    uid: { type: String, required: true, index: true },

    // ── Step 1: Persona ──────────────────────────────────────────────────────
    name: { type: String, required: true, trim: true },
    bio: { type: String, default: '' },
    // e.g. "luxury fashion", "fitness & wellness"
    niche: { type: String, default: '' },
    // e.g. ["instagram", "tiktok", "x"]
    platforms: [{ type: String }],
    // Current campaign goal / objective for this influencer
    goal: { type: String, default: '' },

    // ── X account link ───────────────────────────────────────────────────────
    // XConnection._id linked to this influencer for posting on X
    xConnectionId: { type: String, default: null },

    // ── Step 2: Brand intelligence ───────────────────────────────────────────
    brandSources: [brandSourceSchema],
    // Synthesised brand brief (generated by the agent from all sources)
    brandBrief: { type: String, default: '' },

    // ── Step 3: Avatar (HeyGen) ───────────────────────────────────────────────
    // Physical / style description used as the HeyGen prompt
    imagePrompt: { type: String, default: '' },
    // Up to 4 avatar candidates generated by HeyGen
    // Each entry: { avatarId, groupId, previewImageUrl, previewVideoUrl }
    avatarCandidates: [{ type: Object }],
    // The selected HeyGen look ID (passed as avatar_id to video generation)
    heygenAvatarId: { type: String, default: null },
    // Preview image URL from HeyGen for the selected avatar
    selectedImageUrl: { type: String, default: null },
    // Preview video URL from HeyGen for the selected avatar
    selectedPreviewVideoUrl: { type: String, default: null },

    // ── Agent memory ─────────────────────────────────────────────────────────
    // Long-term strategy document produced by LongTermAgent
    longTermStrategy: { type: String, default: '' },
    longTermStrategyUpdatedAt: { type: Date, default: null },

    // ── Agent scheduling ─────────────────────────────────────────────────────
    // Whether the autonomous posting schedule is active for this influencer
    agentEnabled: { type: Boolean, default: false },
    // Interval in minutes between autonomous posts (minimum 5, default 30)
    agentIntervalMins: { type: Number, default: 30 },
    // 'auto' = post immediately after generation
    // 'approve' = hold as pending_approval until user approves/rejects
    postApprovalMode: { type: String, enum: ['auto', 'approve'], default: 'approve' },
    // Timestamps for scheduler bookkeeping
    agentLastRanAt: { type: Date, default: null },
    agentNextRunAt: { type: Date, default: null },

    // ── Workflow state ───────────────────────────────────────────────────────
    // draft → persona_done → brand_done → image_generated → complete
    status: {
      type: String,
      enum: ['draft', 'persona_done', 'brand_done', 'image_generated', 'complete'],
      default: 'draft',
    },
  },
  { timestamps: true }
)

module.exports = model('Influencer', influencerSchema)
