const { Schema, model } = require('mongoose')

// ── Brand knowledge chunk ────────────────────────────────────────────────────
const brandSourceSchema = new Schema(
  {
    type: {
      type: String,
      enum: ['text', 'pdf', 'url'],
      required: true,
    },
    // Human-readable label (filename, URL, or "Manual text")
    label: { type: String, default: '' },
    // Extracted/raw text content (stored after parsing)
    content: { type: String, default: '' },
    // GCS path if the original file was uploaded (PDFs)
    gcsPath: { type: String, default: null },
  },
  { _id: true, timestamps: true }
)

// ── Main Influencer schema ───────────────────────────────────────────────────
const influencerSchema = new Schema(
  {
    // Owner
    uid: { type: String, required: true, index: true },

    // ── Step 1: Persona ──────────────────────────────────────────────────────
    name: { type: String, required: true, trim: true },
    bio: { type: String, default: '' },
    // e.g. "luxury fashion", "fitness & wellness"
    niche: { type: String, default: '' },
    // e.g. ["instagram", "tiktok", "x"]
    platforms: [{ type: String }],
    // Current campaign goal / objective for this influencer
    goal: { type: String, default: '' },

    // ── X account link ───────────────────────────────────────────────────────
    // XConnection._id linked to this influencer for posting on X
    xConnectionId: { type: String, default: null },

    // ── Step 2: Brand intelligence ───────────────────────────────────────────
    brandSources: [brandSourceSchema],
    // Synthesised brand brief (generated by the agent from all sources)
    brandBrief: { type: String, default: '' },

    // ── Step 3: Image ────────────────────────────────────────────────────────
    // Physical / style description used as the generation prompt
    imagePrompt: { type: String, default: '' },
    // Up to 4 candidate images returned by Gemini (temp signed URLs or GCS paths)
    imageCandidates: [{ type: String }],
    // The selected image path in GCS
    selectedImageGcsPath: { type: String, default: null },
    // Pre-signed URL (regenerated on demand)
    selectedImageUrl: { type: String, default: null },

    // ── Workflow state ───────────────────────────────────────────────────────
    // draft → persona_done → brand_done → image_generated → complete
    status: {
      type: String,
      enum: ['draft', 'persona_done', 'brand_done', 'image_generated', 'complete'],
      default: 'draft',
    },
  },
  { timestamps: true }
)

module.exports = model('Influencer', influencerSchema)
